Update libs
conveyal/jsolines pull request #26
Opened 2017-02-21 15:24 UTC by trevorgerhardt

And ran `mastarm lint --fix`

2017-02-21 15:28 UTC, trevorgerhardt commented
Added a `fix` commit to generate a new release.

2017-03-03 18:02 UTC, evansiroky commented on .travis.yml
> +    - ~/.yarn-cache
Let's change this to:

```
cache:
  yarn: true
```

2017-03-03 18:04 UTC, evansiroky requested changes
Let's get the travis.yml updated and then merge this.

2017-03-03 19:01 UTC, evansiroky commented on .travis.yml
> +  - npm i -g yarn
I think if you include yarn as the cache strategy that yarn will get installed by travis.

2017-04-27 21:57 UTC, trevorgerhardt commented
@mattwigway or @evansiroky could you give this one another review 🙏

2017-04-28 01:25 UTC, evansiroky commented on index.js
> +  project: Function,
[The Function type is unsafe and should be avoided](https://flow.org/en/docs/types/functions/#toc-function-type).

You could rewrite as follows:

```js
type CoordinateArray = [number, number]

...
  interpolation = true
}: {
  surface: Uint8Array,
  width: number,
  height: number,
  cutoff: number,
  project: CoordinateArray => CoordinateArray,
  interpolation: boolean
}) {
```

2017-04-28 01:29 UTC, evansiroky requested changes
Let's try to not use wildcard types like `Function`, `Object`, `any` or `mixed`.

2017-04-28 01:32 UTC, evansiroky commented on .flowconfig
> +[ignore]
Having a config file like this live in the project seems to diverge from keeping config files in mastarm.  But it does sorta seem like this file must exist in order for flow to run, so maybe it's ok.

2017-04-28 01:43 UTC, trevorgerhardt commented on index.js
> +  project: Function,
oh, I had no idea!

2017-04-28 01:44 UTC, trevorgerhardt commented on .flowconfig
> +[ignore]
Yea, when we run `flow-bin` manually we might be able to avoid this. Not sure tho!

2017-04-28 01:48 UTC, evansiroky commented on .flowconfig
> +[ignore]
I didn't see anything in the [docs](https://flow.org/en/docs/cli/) about providing a path for a config file.

2017-04-28 01:51 UTC, evansiroky commented on index.js
> +  project: Function,
I think it may also have the benefit of affecting upstream apps that send typed functions.

2017-05-01 18:54 UTC, trevorgerhardt commented
@evansiroky & @mattwigway this is ready for another look too

2017-05-01 19:02 UTC, evansiroky approved these changes
👍

2017-05-01 19:04 UTC, evansiroky requested changes
Will approve once code coverage is setup correctly

2017-05-01 19:04 UTC, evansiroky commented on .travis.yml
> +  - yarn test -- --coverage
You'll need to specify the coverage directory/files in order for the coverage to work properly.

2017-05-01 19:06 UTC, evansiroky commented on .travis.yml
> +  - yarn test -- --coverage
In this case it would be `yarn test -- --coverage --coverage-paths index.js`

2017-05-01 19:26 UTC, evansiroky approved these changes
I pushed a change to get the coverage working

2017-05-01 19:52 UTC, merged